name: gws-hipaa-oidc-check
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Placeholder OIDC step
        run: |
          echo "Workspace HIPAA baseline - OIDC-capable delivery placeholder."
